"""Narrative-first wrapper around the existing stock footage selector.

It preserves the mature stock acquisition stack, but prevents it from choosing a
visually attractive clip that does not represent the spoken beat.  When no direct
stock match survives, a deterministic literal storyboard is rendered instead.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys

import footage
import hero
import motion
import narrative_fidelity
import profiles
import storyboard
import visual_symbols


class NoNarrativeMatch(RuntimeError):
    def __init__(self, decisions):
        super().__init__("no stock candidate passed narrative fidelity")
        self.decisions = decisions


_CURRENT = {"scene": None, "index": None, "total": None}
_ORIGINAL_RANK = footage.rank


def _gated_rank(query, vids, need=None, genre=None, profile=None):
    scored = _ORIGINAL_RANK(query, vids, need, genre, profile)
    scene = _CURRENT["scene"] or {}
    accepted, decisions = narrative_fidelity.rerank(
        scene, scored, _CURRENT["index"], _CURRENT["total"]
    )
    _CURRENT["decisions"] = decisions
    if narrative_fidelity.direct_match_required(
        scene, _CURRENT["index"], _CURRENT["total"]
    ) and not accepted:
        raise NoNarrativeMatch(decisions)
    return accepted or scored


def _write_report(build_dir: str, rows: list[dict]):
    path = Path(build_dir) / "narrative_fidelity_report.json"
    try:
        current = json.loads(path.read_text(encoding="utf-8"))
        existing = current.get("scenes") if isinstance(current, dict) else []
    except (OSError, ValueError, TypeError):
        existing = []
    merged = {int(row.get("scene_index", -1)): row for row in existing or []}
    for row in rows:
        merged[int(row.get("scene_index", -1))] = row
    path.write_text(json.dumps({
        "schema_version": 1,
        "policy": narrative_fidelity.rules(),
        "scenes": [merged[key] for key in sorted(merged) if key >= 0],
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _timeline_position(script: dict, index: int) -> tuple[float, float]:
    """Use narration time when available; otherwise fall back to scene order."""
    scenes = script.get("scenes") or []
    scene = scenes[index]
    try:
        start = float(scene.get("start"))
        total = max(
            float(item.get("start") or 0.0) + float(item.get("duration") or 0.0)
            for item in scenes
        )
        if total > 0:
            return start, total
    except (TypeError, ValueError):
        pass
    return float(index), float(max(len(scenes), 1))


def _clear_rejected_stock(build_dir: str, scene: dict, index: int) -> None:
    """Remove a cached stock choice before a narrative replacement is selected."""
    output = Path(build_dir) / f"clip_{index:02d}.mp4"
    try:
        output.unlink()
    except OSError:
        pass
    for field in (
        "clip", "stock_id", "pexels_id", "motion_verified", "motion_evidence",
        "motion_source", "source_url", "source_license", "source_title",
        "stock_frame_url", "stock_frame_url_checked", "stock_frame_url_unusable",
    ):
        scene.pop(field, None)


# Standing rule (James): when genuine stock footage cannot be found, the fallback
# is a STILL IMAGE with rich special effects that represents the line — never a
# plain text-box graphic. This bespoke effects still is generated by hero.py.
EFFECTS_STILL_STYLE = motion.EFFECTS_STILL_STYLE  # single source of truth


def _try_effects_still(build_dir, script, index):
    """Generate an appealing special-effects still for one scene. Returns True on
    success. Uses hero.py's pure generated path so the effects survive."""
    scene = script["scenes"][index]
    scene["hero"] = True
    if not scene.get("image_prompt"):
        scene["image_prompt"] = (
            scene.get("semantic_anchor") or scene.get("symbol_query")
            or scene.get("query") or scene.get("text")
        )
    scene["hero_style"] = scene.get("hero_style") or EFFECTS_STILL_STYLE
    try:
        hero.main(build_dir, index)
    except Exception as exc:  # provider down, etc.
        print(f"scene {index}: effects-still generation failed ({exc})")
        scene.pop("hero", None)
        return False
    return bool(scene.get("hero_generated"))


def _render_storyboard(build_dir: str, script: dict, index: int, reason: str,
                       decisions=None, used=None):
    scene = script["scenes"][index]
    # Standing rule: no stock -> a special-effects STILL, not a text-box graphic.
    if _try_effects_still(build_dir, script, index):
        print(f"scene {index}: special-effects still <- {reason}")
        return {
            "scene_index": int(index),
            "result": "effects_still",
            "fallback_reason": f"{reason}; special-effects still (no stock match)",
        }
    try:
        plan = storyboard.render_scene(build_dir, script, index)
    except RuntimeError as exc:
        if "lacks sufficient motion" not in str(exc):
            raise
        # Standing rule: if generation fails, use stock video. A deterministic
        # near-static graphic will fail identically on retry, so re-route to a
        # genuine stock search instead of burning the retry budget. This path
        # only triggers when BOTH literal routes are impossible, so the direct-
        # match gate is relaxed (atmosphere) rather than letting the run die.
        scene["narrative_mode"] = "atmosphere"
        print(f"scene {index}: generated storyboard failed motion gate; "
              f"falling back to genuine stock as atmosphere ({exc})")
        footage.fetch_scene(build_dir, script, index, used if used is not None else set())
        return {
            "scene_index": int(index),
            "result": "stock_fallback_from_storyboard",
            "fallback_reason": f"{reason}; storyboard lacked motion",
            "stock_id": scene.get("stock_id") or scene.get("pexels_id"),
        }
    plan["fallback_reason"] = reason
    if decisions is not None:
        plan["candidate_decisions"] = decisions
    print(f"scene {index}: literal storyboard <- {reason}")
    return plan


def main(build_dir: str, idx: str | None = None):
    script_path = Path(build_dir) / "script.json"
    script = json.loads(script_path.read_text(encoding="utf-8"))
    profile = profiles.resolve(script)
    if visual_symbols.apply_plan(script, profile):
        script_path.write_text(json.dumps(script, indent=1, ensure_ascii=False), encoding="utf-8")
    used = {
        scene.get("stock_id") or scene.get("pexels_id")
        for scene in script.get("scenes", [])
        if scene.get("stock_id") or scene.get("pexels_id")
    }
    if idx is None:
        targets = list(range(len(script.get("scenes", []))))
    else:  # single index or comma-separated batch (one process = one CLIP load)
        targets = [int(part) for part in str(idx).split(",") if part != ""]
    report_rows = []
    footage.rank = _gated_rank
    try:
        for index in targets:
            scene = script["scenes"][index]
            position, span = _timeline_position(script, index)
            _CURRENT.update({
                "scene": scene,
                "index": position,
                "total": span,
                "decisions": [],
            })
            row = {
                "scene_index": index,
                "text": scene.get("text"),
                "query": scene.get("query"),
                "narrative_mode_before": scene.get("narrative_mode"),
            }
            current_id = scene.get("stock_id") or scene.get("pexels_id")
            current_video = {
                "id": current_id,
                "url": scene.get("source_url"),
                "title": scene.get("source_title"),
            }
            rejected_existing = (
                narrative_fidelity.rejected_context(scene, current_video)
                if current_id else None
            )
            existing_ok, existing_coverage, existing_reason = (
                narrative_fidelity.acceptable(scene, current_video, position, span)
                if current_id else (True, 0.0, "no cached stock")
            )
            if rejected_existing or (
                current_id
                and narrative_fidelity.direct_match_required(scene, position, span)
                and not existing_ok
            ):
                reason = (
                    str(rejected_existing.get("reason"))
                    if rejected_existing
                    else f"cached stock failed narrative gate: {existing_reason}"
                )
                _clear_rejected_stock(build_dir, scene, index)
                if storyboard.preferred(scene, position, span):
                    plan = _render_storyboard(build_dir, script, index, reason, used=used)
                    row.update({
                        "result": "literal_storyboard",
                        "existing_anchor_coverage": existing_coverage,
                        "plan": plan,
                    })
                else:
                    try:
                        footage.fetch_scene(build_dir, script, index, used)
                        row.update({
                            "result": "stock_replaced",
                            "stock_id": scene.get("stock_id") or scene.get("pexels_id"),
                            "existing_anchor_coverage": existing_coverage,
                            "candidate_decisions": _CURRENT.get("decisions") or [],
                        })
                    except (NoNarrativeMatch, SystemExit) as exc:
                        decisions = getattr(exc, "decisions", _CURRENT.get("decisions") or [])
                        plan = _render_storyboard(
                            build_dir, script, index,
                            "cached stock failed and no direct replacement survived",
                            decisions, used=used,
                        )
                        row.update({
                            "result": "literal_storyboard",
                            "existing_anchor_coverage": existing_coverage,
                            "candidate_decisions": decisions,
                            "plan": plan,
                        })
            elif storyboard.preferred(scene, position, span):
                plan = _render_storyboard(build_dir, script, index, "literal mechanism preferred", used=used)
                row.update({"result": "literal_storyboard", "plan": plan})
            else:
                try:
                    footage.fetch_scene(build_dir, script, index, used)
                    row.update({
                        "result": "stock",
                        "stock_id": scene.get("stock_id") or scene.get("pexels_id"),
                        "candidate_decisions": _CURRENT.get("decisions") or [],
                    })
                except NoNarrativeMatch as exc:
                    plan = _render_storyboard(
                        build_dir, script, index,
                        "no stock candidate represented the spoken anchors",
                        exc.decisions, used=used,
                    )
                    row.update({
                        "result": "literal_storyboard",
                        "candidate_decisions": exc.decisions,
                        "plan": plan,
                    })
                except SystemExit as exc:
                    message = str(exc)
                    if "no results" not in message and "no candidate" not in message:
                        raise
                    plan = _render_storyboard(
                        build_dir, script, index,
                        "stock search could not produce a usable direct match",
                        _CURRENT.get("decisions"), used=used or [],
                    )
                    row.update({"result": "literal_storyboard", "plan": plan})
            script_path.write_text(json.dumps(script, indent=1, ensure_ascii=False), encoding="utf-8")
            report_rows.append(row)
    finally:
        footage.rank = _ORIGINAL_RANK
    _write_report(build_dir, report_rows)
    visual_symbols.write_report(build_dir, script, profile)


def cli(argv=None):
    args = list(argv or sys.argv[1:])
    if not args:
        raise SystemExit("usage: storyline_footage.py <build_dir> [scene_index|credits|pin]")
    build_dir = args[0]
    if len(args) > 1 and args[1] == "credits":
        footage.write_credits(build_dir)
        return 0
    if len(args) > 1 and args[1] == "pin":
        footage.pin(
            build_dir, int(args[2]), args[3], args[4] if len(args) > 4 else None,
        )
        return 0
    main(build_dir, args[1] if len(args) > 1 else None)
    return 0


if __name__ == "__main__":
    raise SystemExit(cli())
